#
#  Makefile.fpc for hash units example
#

[target]
programs=MDTest GeneratePascalShaHashes

[require]
packages=

[install]
fpcpackage=y

[compiler]
options=-Fu"..;../HashLib/HashLib/src/*"

[default]
fpcdir=${FPCDIR}





