#
#  Makefile.fpc for hash units example
#

[target]
programs=MDTest GeneratePascalShaHashes BCryptHashTest Base64Test HashEquals

[require]
packages=

[install]
fpcpackage=y

[compiler]
options=-Fu"..;../HashLib/HashLib/src/*"

[default]
fpcdir=${FPCDIR}





